INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (7, 5, 'Excelente atención y comida deliciosa. Volveré pronto.', TO_TIMESTAMP('2025-06-15 13:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (14, 4, 'Todo muy rico, pero demoraron un poco en servir.', TO_TIMESTAMP('2025-06-15 19:10:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (23, 5, 'Ambiente agradable y sabores auténticos. Recomendado.', TO_TIMESTAMP('2025-06-16 14:25:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (31, 3, 'Buena comida, pero esperaba más variedad en bebidas.', TO_TIMESTAMP('2025-06-16 18:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (42, 4, 'El postre estuvo increíble, pero el plato principal normal.', TO_TIMESTAMP('2025-06-17 12:15:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (50, 5, 'Todo fue perfecto, desde el servicio hasta la comida.', TO_TIMESTAMP('2025-06-17 20:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (63, 4, 'El mozo fue muy amable, pero el plato llegó un poco frío.', TO_TIMESTAMP('2025-06-18 13:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (72, 5, 'Una experiencia maravillosa. ¡Felicitaciones al chef!', TO_TIMESTAMP('2025-06-18 15:20:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (88, 3, 'El sabor estuvo bien, pero podrían mejorar la presentación.', TO_TIMESTAMP('2025-06-19 14:40:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (95, 4, 'Disfrutamos mucho del menú del día, buena relación calidad/precio.', TO_TIMESTAMP('2025-06-19 19:10:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (102, 5, 'El lomo saltado fue de los mejores que he probado.', TO_TIMESTAMP('2025-06-20 12:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (109, 4, 'Muy buen ambiente y excelente limpieza.', TO_TIMESTAMP('2025-06-20 17:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (115, 5, 'Recomendadísimo, sobre todo el ají de gallina.', TO_TIMESTAMP('2025-06-21 13:15:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (120, 3, 'Estuvo bien, aunque el servicio fue un poco lento.', TO_TIMESTAMP('2025-06-21 19:25:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (126, 5, 'Nos encantó la torta helada. Volveremos con amigos.', TO_TIMESTAMP('2025-06-22 14:10:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (130, 4, 'Buena atención, aunque faltó un poco de sazón.', TO_TIMESTAMP('2025-06-22 20:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (3, 5, 'De lo mejor que he probado últimamente.', TO_TIMESTAMP('2025-06-23 13:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (17, 4, 'Los jugos estuvieron muy frescos y sabrosos.', TO_TIMESTAMP('2025-06-23 18:20:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (28, 5, 'Buen trato y platos servidos a tiempo.', TO_TIMESTAMP('2025-06-24 14:50:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (36, 4, 'Todo correcto, aunque esperaba un poco más del postre.', TO_TIMESTAMP('2025-06-24 19:40:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (45, 5, 'Un lugar acogedor y muy bien decorado.', TO_TIMESTAMP('2025-06-25 12:05:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (53, 4, 'Nos atendieron muy bien. Platos con buena presentación.', TO_TIMESTAMP('2025-06-25 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (60, 5, 'Muy sabroso todo. Ideal para almorzar en familia.', TO_TIMESTAMP('2025-06-26 13:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (66, 3, 'Buena atención, pero el plato principal se enfrió.', TO_TIMESTAMP('2025-06-26 20:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (73, 5, 'Todo excelente. ¡Felicitaciones al equipo!', TO_TIMESTAMP('2025-06-27 12:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (80, 4, 'El mozo fue muy atento y cordial.', TO_TIMESTAMP('2025-06-27 18:15:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (92, 5, 'Comida abundante y muy sabrosa.', TO_TIMESTAMP('2025-06-28 13:15:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (100, 3, 'Bien, aunque faltó temperatura en el café.', TO_TIMESTAMP('2025-06-28 19:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (110, 4, 'Muy buena experiencia general.', TO_TIMESTAMP('2025-06-29 14:10:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO resena (id_factura, calificacion, comentario, fecha) VALUES (125, 5, 'Todo delicioso. Volveremos seguro.', TO_TIMESTAMP('2025-06-30 13:50:00', 'YYYY-MM-DD HH24:MI:SS'));
