CREATE TABLE "mytable" (
  "-- =============================================" text
);

INSERT INTO "mytable" ("-- =============================================")
VALUES
('-- FUNCTION'),
('-- ============================================='),
('-- Consulta para mostrar el promedio de calificación de todos los trabajadores'),
('create or replace FUNCTION fnc_promedio_calificacion_trabajador(p_id_trabajador NUMBER)'),
('RETURN NUMBER'),
('IS'),
('v_promedio NUMBER;'),
('BEGIN'),
('SELECT AVG(R.CALIFICACION)'),
('INTO v_promedio'),
('FROM ADMIN.RESENA R'),
('JOIN ADMIN.FACTURA F ON R.ID_FACTURA = F.ID'),
('JOIN ADMIN.PEDIDO P ON F.PEDIDO_ID = P.ID'),
('WHERE P.TRABAJADOR_ID = p_id_trabajador;'),
('RETURN NVL(v_promedio'),
('END;'),
('-- Monto total facturado en pedidos hechos por un trabajador'),
('create or replace FUNCTION fnc_total_facturado_por_trabajador(p_id_trabajador NUMBER)'),
('RETURN NUMBER'),
('IS'),
('v_total NUMBER;'),
('BEGIN'),
('SELECT NVL(SUM(F.MONTO_FINAL)'),
('INTO v_total'),
('FROM ADMIN.FACTURA F'),
('JOIN ADMIN.PEDIDO P ON F.PEDIDO_ID = P.ID'),
('WHERE P.TRABAJADOR_ID = p_id_trabajador;'),
('RETURN v_total;'),
('END;'),
('-- Devuelve cuántos pedidos hizo un trabajador'),
('create or replace FUNCTION FNC_TOTAL_PEDIDOS_TRABAJADOR(P_ID_TRABAJADOR NUMBER)'),
('RETURN NUMBER'),
('IS'),
('V_TOTAL NUMBER;'),
('BEGIN'),
('SELECT COUNT(*) INTO V_TOTAL'),
('FROM ADMIN.PEDIDO'),
('WHERE TRABAJADOR_ID = P_ID_TRABAJADOR;'),
('RETURN V_TOTAL;'),
('END;'),
('-- Devuelve el total de unidades vendidas por cada producto'),
('create or replace FUNCTION fnc_total_unidades_vendidas(p_id_producto NUMBER)'),
('RETURN NUMBER'),
('IS'),
('v_total NUMBER;'),
('BEGIN'),
('SELECT NVL(SUM(CANTIDAD)'),
('INTO v_total'),
('FROM ADMIN.PEDIDO_PRODUCTO'),
('WHERE PRODUCTO_ID = p_id_producto;'),
('RETURN v_total;'),
('END;');
