-- =============================================
-- TABLAS NUEVAS PARA MEJORA DEL SISTEMA
-- =============================================

-- Tabla: RESENA
-- Propósito: Almacenar reseñas de clientes sobre su experiencia general en el restaurante.
-- Vinculada a la tabla FACTURA para asegurar autenticidad del feedback.
CREATE TABLE RESENA (
  ID_RESENA     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ID_FACTURA    NUMBER NOT NULL REFERENCES FACTURA(ID),
  CALIFICACION  NUMBER CHECK (CALIFICACION BETWEEN 1 AND 5),
  COMENTARIO    VARCHAR2(300),
  FECHA         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla: QUEJA
-- Propósito: Registrar quejas específicas sobre trabajadores, asociadas a una factura.
-- Permite seguimiento del estado de cada queja (pendiente, resuelta o descartada).
CREATE TABLE QUEJA (
  ID_QUEJA       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ID_FACTURA     NUMBER NOT NULL REFERENCES FACTURA(ID),
  ID_TRABAJADOR  NUMBER NOT NULL REFERENCES TRABAJADOR(ID),
  DESCRIPCION    VARCHAR2(300) NOT NULL,
  FECHA          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ESTADO         VARCHAR2(20) DEFAULT 'pendiente'
                 CHECK (ESTADO IN ('pendiente', 'resuelta', 'descartada'))
);

-- Tabla: TURNO
-- Propósito: Registrar los turnos de trabajo de cada empleado, incluyendo fecha y hora de inicio y fin.
-- Mejora la organización interna y el control de horarios.
CREATE TABLE TURNO (
  ID_TURNO       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ID_TRABAJADOR  NUMBER NOT NULL REFERENCES TRABAJADOR(ID),
  INICIO_TURNO   DATE NOT NULL,
  FIN_TURNO      DATE NOT NULL
);
